#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: circle_agent
# REQUIRE: DAEMON NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name="circle_agent"
rcvar="circle_agent_enable"
command="/usr/local/bin/python /root/agent.py"
pidfile="/var/run/${name}.pid"

load_rc_config $name
run_rc_command "$1"
