#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: circle_agent
# REQUIRE: DAEMON NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name="circle_agent"
rcvar="circle_agent_enable"
pidfile="/var/run/${name}.pid"
start_cmd="do_start"
stop_cmd="do_stop"

do_start()
{
	PATH=${PATH}:/usr/local/bin/

	/usr/sbin/daemon -P ${pidfile} -r /usr/local/bin/python /root/agent/agent.py
}

do_stop()
{
	if [ -f ${pidfile} ]
	then
		kill `cat ${pidfile}`
	fi
}

load_rc_config $name
run_rc_command "$1"
