#!/usr/bin/env python

import notify

if __name__ == '__main__':
    try:
        notify.accept()
    except:
        print "There was an unknown error while trying to renew this vm, please do it manually!"